clone_depth: 1

# use Windows Server 2016 (https://appveyor.tenderapp.com/discussions/questions/3424-confusion-about-how-to-change-to-os)
image: Visual Studio 2017

# Install scripts. (runs after repo cloning)
install:
  # https://answers.microsoft.com/en-us/windows/forum/windows_10-win_cortana/reinstall-microsoft-edge/67f129e2-4d5e-42ca-9c89-466b29082a51
  - ps: Get-AppXPackage -AllUsers -Name Microsoft.MicrosoftEdge | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml" –Verbose}
  - refreshenv
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - ps: Write-Host (Get-WmiObject -class Win32_OperatingSystem).Caption
  - node --version
  - npm --version
  # run tests
  - npm run test:windows

# Don't actually build.
build: off

# build cache to preserve files/folders between builds
cache:
  - node_modules  # local npm modules
